In [1]:
# section notebook - https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/introduction-to-numpy-video.ipynb
# section notes - https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/introduction-to-numpy.ipynb

In [2]:
import numpy as np

## DataTypes && Attributes

In [38]:
# Numpy's main data type is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [39]:
type(a1)

numpy.ndarray

In [40]:
a2 = np.array([[1, 2.2, 3.5],
             [4.5, 5, 6.1]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [41]:
a2

array([[1. , 2.2, 3.5],
       [4.5, 5. , 6.1]])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [43]:
a1.shape

(3,)

In [44]:
a2.shape

(2, 3)

In [45]:
a3.shape

(2, 3, 3)

In [46]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [47]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [48]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [49]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [50]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.2  3.5
1  4.5  5.0  6.1

## 2. Creating arrays

In [3]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [4]:
sample_array.dtype

dtype('int64')

In [5]:
ones = np.ones((2,3))

In [6]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
ones.dtype

dtype('float64')

In [8]:
type(ones)

numpy.ndarray

In [9]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [16]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[0, 1, 6, 7, 5],
       [7, 8, 9, 8, 2],
       [9, 9, 4, 6, 2]])

In [17]:
random_array.size

15

In [18]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.32295547, 0.02932279, 0.24171763],
       [0.14764508, 0.62197269, 0.88747237],
       [0.38136179, 0.96089856, 0.23764172],
       [0.65653168, 0.42372894, 0.87666776],
       [0.91330201, 0.64023503, 0.34645572]])

In [19]:
random_array_2.shape

(5, 3)

In [20]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.96573941, 0.83829061, 0.78921021],
       [0.51950523, 0.19681575, 0.78887525],
       [0.14544737, 0.01697403, 0.36228331],
       [0.67831292, 0.85473545, 0.48486667],
       [0.69512925, 0.7924561 , 0.98350259]])

In [31]:
# Pseudo random numbers
# np.random.seed(seed=9999) # generates unchanged random numbers when seed parameter is given
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[6, 1, 6],
       [5, 5, 9],
       [6, 8, 0],
       [8, 1, 5],
       [3, 1, 0]])

In [32]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [34]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.20484909, 0.49076589, 0.37238469],
       [0.47740115, 0.36589039, 0.83791799],
       [0.76864751, 0.31399468, 0.57262533],
       [0.27604905, 0.45284293, 0.35297837],
       [0.65739946, 0.37035108, 0.45909298]])

## 3. Viewing arrays and matrices

In [35]:
random_array_4

array([[6, 1, 6],
       [5, 5, 9],
       [6, 8, 0],
       [8, 1, 5],
       [3, 1, 0]])

In [36]:
np.unique(random_array_4)

array([0, 1, 3, 5, 6, 8, 9])

In [51]:
a1

array([1, 2, 3])

In [52]:
a2

array([[1. , 2.2, 3.5],
       [4.5, 5. , 6.1]])

In [53]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [54]:
a1[0]

np.int64(1)

In [56]:
a2.shape

(2, 3)

In [57]:
a2[0]

array([1. , 2.2, 3.5])

In [58]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [61]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 0, 9, 8, 2],
         [0, 5, 5, 0, 9],
         [0, 8, 4, 5, 1],
         [4, 0, 7, 2, 0]],

        [[3, 9, 8, 3, 7],
         [1, 0, 1, 4, 6],
         [1, 0, 1, 0, 1],
         [8, 4, 1, 6, 8]],

        [[5, 2, 4, 7, 4],
         [1, 2, 8, 5, 2],
         [9, 6, 2, 5, 7],
         [7, 5, 5, 6, 0]]],


       [[[6, 4, 6, 2, 6],
         [8, 7, 0, 5, 8],
         [9, 7, 7, 6, 2],
         [5, 6, 1, 9, 3]],

        [[4, 0, 3, 5, 6],
         [4, 0, 4, 1, 5],
         [2, 4, 8, 7, 5],
         [7, 5, 3, 7, 6]],

        [[2, 3, 1, 1, 8],
         [4, 2, 1, 7, 0],
         [8, 8, 1, 2, 3],
         [0, 1, 1, 5, 5]]]])

In [62]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [67]:
# Get the first 3 numbers of the inner most arrays
a4[:, :, :, :3]

array([[[[0, 0, 9],
         [0, 5, 5],
         [0, 8, 4],
         [4, 0, 7]],

        [[3, 9, 8],
         [1, 0, 1],
         [1, 0, 1],
         [8, 4, 1]],

        [[5, 2, 4],
         [1, 2, 8],
         [9, 6, 2],
         [7, 5, 5]]],


       [[[6, 4, 6],
         [8, 7, 0],
         [9, 7, 7],
         [5, 6, 1]],

        [[4, 0, 3],
         [4, 0, 4],
         [2, 4, 8],
         [7, 5, 3]],

        [[2, 3, 1],
         [4, 2, 1],
         [8, 8, 1],
         [0, 1, 1]]]])

In [69]:
a5 = np.random.randint(10, size=(2,2,3,4,5))
a5

array([[[[[8, 4, 7, 8, 3],
          [3, 4, 0, 2, 8],
          [8, 2, 5, 6, 8],
          [0, 7, 3, 7, 8]],

         [[5, 5, 0, 6, 4],
          [1, 8, 3, 9, 5],
          [4, 7, 3, 9, 6],
          [6, 5, 9, 2, 7]],

         [[7, 6, 3, 2, 0],
          [4, 9, 3, 0, 1],
          [0, 3, 2, 0, 5],
          [8, 3, 9, 2, 4]]],


        [[[9, 5, 1, 7, 6],
          [6, 3, 9, 9, 9],
          [8, 8, 6, 4, 7],
          [4, 8, 0, 0, 9]],

         [[3, 5, 5, 7, 1],
          [8, 8, 0, 7, 0],
          [6, 1, 9, 8, 8],
          [1, 5, 9, 1, 1]],

         [[9, 6, 3, 6, 9],
          [3, 6, 1, 0, 6],
          [6, 0, 6, 9, 0],
          [8, 1, 1, 2, 1]]]],



       [[[[3, 0, 3, 5, 4],
          [3, 8, 1, 5, 1],
          [9, 9, 1, 2, 9],
          [6, 0, 0, 8, 6]],

         [[0, 0, 1, 5, 1],
          [7, 4, 5, 5, 1],
          [4, 1, 5, 8, 0],
          [7, 0, 0, 8, 6]],

         [[3, 4, 4, 6, 5],
          [4, 6, 7, 6, 5],
          [4, 1, 8, 0, 5],
          [1, 7, 1, 9, 4]]],


  

## 4. Manipulating & comparing arrays

In [70]:
a1

array([1, 2, 3])

In [73]:
ones = np.ones(3)

In [74]:
a1 + ones

array([2., 3., 4.])

In [75]:
a1 - ones

array([0., 1., 2.])

In [76]:
a1 * ones

array([1., 2., 3.])

In [78]:
a1

array([1, 2, 3])

In [77]:
a2

array([[1. , 2.2, 3.5],
       [4.5, 5. , 6.1]])

In [79]:
a1 * a2

array([[ 1. ,  4.4, 10.5],
       [ 4.5, 10. , 18.3]])

In [82]:
# How can you reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array?"
# a2 * a3
a2[:2, :2] * a3[:2, :2]

ValueError: operands could not be broadcast together with shapes (2,2) (2,2,3) 

In [83]:
a1 / ones

array([1., 2., 3.])

In [85]:
a2 / a1

array([[1.        , 1.1       , 1.16666667],
       [4.5       , 2.5       , 2.03333333]])

In [86]:
# Floor division removes the decimals
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [87]:
a2 ** 2

array([[ 1.  ,  4.84, 12.25],
       [20.25, 25.  , 37.21]])

In [88]:
np.square(a2)

array([[ 1.  ,  4.84, 12.25],
       [20.25, 25.  , 37.21]])

In [89]:
np.add(a1, ones)

array([2., 3., 4.])

In [91]:
a1 / 2

array([0.5, 1. , 1.5])

In [92]:
a1 % 2

array([1, 0, 1])

In [93]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [94]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])